#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PokeBattle.Resource", IsApplication=true)]

namespace PokeBattle
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bellsprout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BellsproutCode = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Bulbasaur = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BulbasaurCode = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Charmander = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CharmanderCode = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Charmeleon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CharmeleonCode = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Ivysaur = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int IvysaurCode = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Machop = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int MachopCode = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Pidgey = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int PidgeyCode = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int PokebattleLogo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Pokemonlogo1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Pokemonlogo4 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Pokemonlogo5 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Squirtle = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int SquirtleCode = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int StartingLogos = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Wartortle = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int WartortleCode = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int Continue = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int Move1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Move2 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int Move3 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int Move4 = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int fightButton = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int healButton = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int imageView1 = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int imageView2 = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int imageView3 = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout2 = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout3 = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout4 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout5 = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout6 = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int moneyButton = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int pokedexButton = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int textBox = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FightActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainScreenLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int Bulbasaur = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int BulbasaurMoveString = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int Charmander = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int CharmanderMoveString = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int Chose_Starter1 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Chose_Starter2 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Chose_Starter3 = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int Squirtle = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int SquirtleMoveString = 2130968591;
			
			// aapt resource value: 0x7f040003
			public const int Starter1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Starter2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Starter3 = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int Starter_String = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int Test_String = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int title_money = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
